### ISSUE TITLE
Where to ask question about wasmi?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [paritytech/wasmi#166]
Is there a better place then here, in issues, to ask questions about using wasmi?

In particular, I have functions like this:

```
extern crate serde_json;

use serde_json::Value as JsonValue;
use serde_json::Value::String as JsonString;

#[no_mangle]
pub extern "C" fn run(mut inputs: Vec<Vec<JsonValue>>) -> (Option<JsonValue>, bool) {
```

written in rust, compiled to wasm, that I then want to call elsewhere (after loading the ModuleRef).

Is there any example code or hints on how to convert such complex input and output types to and from RuntimeValues, and call functions with that signature?

```
        let res = module.invoke_export("run", &[RuntimeValue::from(inputs)],
                                  &mut NopExternals).unwrap().unwrap();
```

Thanks for any help here or pointers to where better to ask such question.

**Comment by pepyakin** [comment]
That's a great question!

First, I'd recommend against using `Vec` and even a tuple, since they are Rust types which don't have stable ABI representation. I'd recommend even more so against using `JsonValue` since it's representation additionally depends on `serde` package.

Basically you would need to write wrappers that use only ABI stable values and can be safely passed via ABI boundary. 

It is hard to recommend anything specific, but it looks like you deal with some JS input and JS output. So what you could do is some how allocate a buffer of memory in the wasm sandbox, then [copy](https://paritytech.github.io/wasmi/wasmi/struct.MemoryInstance.html#method.set) JS serialized memory into the allocated buffer and then call the entrypoint function with a pointer to the buffer. You might want to [construct](https://doc.rust-lang.org/1.32.0/alloc/slice/fn.from_raw_parts.html) a slice from the input buffer.

Then you do approximately the same, in the reverse direction when you are returning the data.

The best option to reach us would be using [Riot](riot.im) on [Parity Wasm public channel](https://matrix.to/#/!OoAWoTkXgxMLnLwGPO:matrix.parity.io?via=matrix.parity.io&via=matrix.org).

**Comment by andrewdavidmackenzie** [comment]
Thanks for response....

I wonder if anyone is working on a "conversion layer" to/from complex rust
types to wasm abi-safe types?

Kind of like what serde can do to derive serialize/deserialize to/from a
wire format, but to/from wasm ABI types?

It's kind of done by wasm-bindgen for JS no?

**Comment by andrewdavidmackenzie** [comment]
Are you suggesting passing in the serialized Json, and have the function in wasm do the deserialization (using serde, compiled with the function) and then re-serialize the output back to rust?

**Comment by andrewdavidmackenzie** [comment]
Something along the lines of this:

http://timryan.org/2019/01/22/exporting-serde-types-to-typescript.html

but instead of emitting a typescript type definition, it would generate the code to assemble the RuntimeValues to pass to the module_ref.invoke_export() method?
