### ISSUE TITLE
Cannot believe wasmi slower than Go's Life

### ISSUE THREAD

**Issue by vitali2y** [paritytech/wasmi#170]
See  [here](https://github.com/perlin-network/life#benchmarks).

**Comment by pepyakin** [comment]
Yeah, we are familiar with these results. However, we are failing to reproduce the same results. The results we got, AFAIR, had about 10-20% difference at most, but for sure not much close to 2x difference presented there. (Ignoring life's JIT)

The difference is quite explainable, e.g. they went further in prepreprocessing the code and Go has certain advantages over Rust in some places. 

Performance par is definitely achievable, however, I'd say it is a non-goal for wasmi. We performed most obvious low-hanging fruit optimizations and not sure if it makes sense to continue these efforts, since they take time and introduce complexity.

The better approach in our view is to spend efforts in different directions. For example, even the simplest native compiler will produce code that is orders of magnitude(s) faster than a typical interpreter. That said, wasmi would be useful for prototyping and checking the correctes of the said compiler.
