### ISSUE TITLE
Error when using in conjunction with TermColor

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [paritytech/wasmi#211]
I have a problem that I am totally lost on. I only mention it here in case you have ideas - as I suspect this will be a big rabbit hole for me if not.

My program uses wasmi to load a .wasm and execute a function. All works fine.
I have a small lib to handle output (a logger).

When I update my logging lib to generate colored output using the TermColor crate, then wasm function execution returns this error:

`Wasm invoke_export(): Trap(Trap { kind: Unreachable })`

I couldn't believe they are related and struggle to see how - unless it is something to do with stdout/stderr locking or similar?

**Comment by pepyakin** [comment]
I think this issue is not related to wasmi per se, since wasmi, or rather WebAssembly, doesn't have any notion of terminal color, nor terminal, nor even a standard library. So this is most likely a problem in the code that you are using.

That said, I agree that wasmi could use some debugging capabilities to tell at least the call stack where the trap happened.
