### ISSUE TITLE
WASI support?

### ISSUE THREAD

**Issue by vshymanskyy** [paritytech/wasmi#229]
Is WASI support planned? I believe it would be beneficial to have at least minimal functionality.

**Comment by pepyakin** [comment]
Hey! There are no plans to integrate WASI at the moment. 

To be honest, I am not sure that wasmi is a good fit for that kind of use case. There are several thoughts about this. 

wasmi is rather a conservative engine. It doesn't participate in the development in of 🦄future features nor it tries to squeeze the last bit of performance. The reasons for that on one hand is the lack of manpower to work, review and test changes and at the other hand it is being a backbone for systems that host amounts at least with 6 zeros.

**Comment by vshymanskyy** [comment]
Thx for explanation!

**Comment by flavio** [comment]
Sorry to comment on this old issue, I've just noticed that the README of wasmi 0.24 changed the statement about WASI support to:
> Experimental support via the wasmi_wasi crate.

I've looked into the [`wasmi_crate`](https://crates.io/crates/wasmi_wasi/versions) but I couldn't find a valid version.
Is there some published code I can play with?

CC @Robbepop, who seems to be the one working on `wasmi_wasi`

**Comment by Robbepop** [comment]
@flavio We do have WASI support now via the [`wasmi_wasi` crate](https://github.com/paritytech/wasmi/tree/master/crates/wasi).
However, since support is still eperimental (missing lots of tests) we did not yet publish the `wasmi_wasi` crate to crates.io.
However, you can still use it by cloning the repo and using it from sources.
Also there is a small [`HelloWorld` test](https://github.com/paritytech/wasmi/blob/master/crates/wasi/tests/wasi_wat.rs) available that demonstrates how to use the WASI support in `wasmi`.
