### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by mpapierski** [paritytech/wasmi#252]
Hello,

I'm trying to update `parity-wasm` from 0.41 to 0.42 in our project although wasmi 0.8 still depends on 0.41 and it results in a complaint from the compiler that I'm trying to use two different versions of a crate. I noticed dependencies are fixed in current wasmi master in commit f5fd480260490ff0de455017229caf7baee68195. It would be really appreciated if we can get a new release on crates.io to avoid pinning our dependencies to git repo.

I'm thinking 0.8.1 or either 0.9, as I underand bumping to 0.8.1 could force people to upgrade parity-wasm which might be considered breaking change

Thanks!

**Comment by captbaritone** [comment]
I'd also be interested in seeing a release. For tests in my [side project](https://github.com/captbaritone/eel-wasm/pull/53), I'm currently depending `wasmi = { git = "https://github.com/paritytech/wasmi", branch = "master" }` in order to get support for mutable imported globals. 

Thanks for the fantastic project!

**Comment by Robbepop** [comment]
Closed since we already are on version `9.1`.
