### ISSUE TITLE
Could `libm` be removed ?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#446]
It seems that no_std could works well without `libm`. I want to know ther reason about import it? For performance?

**Comment by Robbepop** [comment]
My gut feeling is "no" but I forgot why. :upside_down_face: 
In the past we used `libm` because the Rust standard library did not support the required floating point instructions under certain circumstances such as compilation to WebAssembly in `no_std` mode.
I don't know if this is still the case ...

Importants links:

- https://github.com/rust-lang/libm
- https://github.com/paritytech/wasmi/issues/240
- https://github.com/paritytech/wasmi/pull/241

**Comment by Robbepop** [comment]
We indeed need `libm` since some `f32` and `f64` methods such as `fract` and `trunc` are not available in Rust's `core` library unfortunately. This may change in the future though since some people are working on that.

Compare the following docs for `f32`:

- `std`: https://doc.rust-lang.org/std/primitive.f32.html
- `core`: https://doc.rust-lang.org/core/primitive.f32.html
