### ISSUE TITLE
`Engine` deadlocks when calling from host function to WASM.

### ISSUE THREAD

**Issue by Berrysoft** [paritytech/wasmi#567]
The `Engine` locks when calling a WASM function. If the WASM function calls a host function, and the host function calls another WASM function, it deadlocks.

```
         lock                                deadlock
host ------------> WASM ------------> host ------------> WASM
```

Unfortunately, my use case heavily depends on this calling routine. The host function calls a WASM function to make an ABI-compatible allocation. The same code passes on Wasmtime. It seems not a simple problem to solve, but I think it is better to point it out.

**Comment by Robbepop** [comment]
I am aware of this problem. I was not aware that Wasmtime allows this behavior though. However, it is actually simpler with a JIT compiler compared to an interpreter since there is much more state in an interpreter that needs to be carried over to new function executions.
As you pointed out this won't be simple to implement on the `wasmi` side. Can you tell me more about your use case in particular? I thought it was not very important so far which is why we never focused on fixing this issue.

**Comment by Berrysoft** [comment]
Well, if it is difficult to solve, it's OK. I'll try to remove these allocations to make sure no deadlocks :)

**Comment by Robbepop** [comment]
@Berrysoft btw thank you a lot for writing all those issues! That really help us improving `wasmi`. :blush:

**Comment by Robbepop** [comment]
Closed in favor of https://github.com/paritytech/wasmi/issues/572.
