### ISSUE TITLE
`extract_imports` and `extract_memories` do `push_memory` duplicated  in`Module::instantiate`

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/wasmi#587]
When building module, `memory` is collected by both `imports` and `memories` now.

What I means `Memory::new` is called twice when there is only one import  "env" "memory".
The first one is called by me for pass it to linker, but the second one is called by `extract_memories`.
But if we do not import memory, `Memory::new` never be called.

**Comment by Robbepop** [comment]
Sorry but I don't understand at all what exactly the problem is supposed to be here.

**Comment by yjhmelody** [comment]
Ok, I will add a test to show it.

**Comment by yjhmelody** [comment]
See #589

**Comment by Robbepop** [comment]
Thank you for the draft PR.
So it seems you want support for Wasm files with multiple memories which is not supported in Wasm MVP.
There is a Wasm proposal call `multi-memories` which will enable support for having more than just one linear memory at per Wasm file: https://github.com/WebAssembly/multi-memory

However, there are currently no plans to support that in `wasmi` since it will likely introduce overhead for memory instructions.

**Comment by yjhmelody** [comment]
Hi @Robbepop Could you give me some feedback?

**Comment by Robbepop** [comment]
Sorry, my initial answer was wrong, so I deleted it again, then I forgot to write another. I wrote a new answer as review comment to your PR.
