### ISSUE TITLE
`wasmi_cli`: Support targeting OpenWrt `mipsel-unknown-linux-musl`

### ISSUE THREAD

**Issue by huntc** [paritytech/wasmi#654]
Perhaps unintended for support, so please close if necessary.

I'm able to build OpenWrt `mipsel-unknown-linux-musl` targets for my Rust projects, so I thought I'd try it against wasmi. I'm discovering problems during the linking of the `wasmi_cli`. FIrstly, this is how I set up my OpenWrt environment:

```
export STAGING_DIR=/Volumes/OpenWrt/openwrt/staging_dir
export PATH=$STAGING_DIR/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin:$PATH
export MIPSEL_UNKNOWN_LINUX_MUSL_OPENSSL_DIR=$STAGING_DIR/host
```

...then to compile:

```
CC="mipsel-openwrt-linux-musl-gcc" cargo build --release --target=mipsel-unknown-linux-musl
```

...which ultimately yields:

```
  = note: clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
          ld: warning: directory not found for option '-Lsrc/backend/linux_raw/arch/outline/release'
          ld: unknown option: --as-needed
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, it does appear that I can build `wasmi/crates/wasmi` itself, so I am able to continue my experiments.

**Comment by Robbepop** [comment]
Hi @huntc
The `wasmi` interpreter was designed to run on embedded platforms such as `wasm32-unknown-unknown` and in our CI we also build for the `thumbv7em-none-eabi` since it has no `std` library support. This is true for all crates but the `wasmi_cli` crate. The `wasmi_cli` crate is special in that it is a CLI tool and therefore requires the use of `std` in Rust. At least to my knowledge building a CLI tool in Rust without `std` support is going to be a rough experience. Please feel free to teach me wrong. :)

I am not sure if that is the problem here since we do not directly control flags such as `-pie` and `ld`'s `--as-needed` flag. Therefore I am probably missing the information to help you out with your endeavor.

If you come up with an idea how `wasmi_cli` can be build on more platforms and especially yours, then I am happy to hear that. :)

**Comment by huntc** [comment]
> Hi @huntc The `wasmi` interpreter was designed to run on embedded platforms such as `wasm32-unknown-unknown` and in our CI we also build for the `thumbv7em-none-eabi` since it has no `std` library support. This is true for all crates but the `wasmi_cli` crate. The `wasmi_cli` crate is special in that it is a CLI tool and therefore requires the use of `std` in Rust. At least to my knowledge building a CLI tool in Rust without `std` support is going to be a rough experience. Please feel free to teach me wrong. :)

Thanks for getting back to me! To be clear, OpenWrt is a std target for Rust, and I've built a number of CLIs for it.

> 
> I am not sure if that is the problem here since we do not directly control flags such as `-pie` and `ld`'s `--as-needed` flag. Therefore I am probably missing the information to help you out with your endeavor.
> 
> If you come up with an idea how `wasmi_cli` can be build on more platforms and especially yours, then I am happy to hear that. :)

Wilco. Thanks!

**Comment by Robbepop** [comment]
Hi @huntc, trying to clean up the backlog. This issue seems to be inactive and also I kinda feel like it isn't something that can be resolved in `wasmi` itself but rather in the Rust tech stack for the OpenWrt `mipsel-unknown-linux-musl` target.

Do you confirm? If so I'd like to close this and if needed we can re-open or start a discussion in a GitHub discussions thread.

**Comment by huntc** [comment]
Yeah, sorry I’ve not hard time to pursue this. I will close. Thanks for the dialogue.

**Comment by huntc** [comment]
Months later, I came back to this. I simply required a .cargo/config.toml file in the cli folder with:

```
[target.mipsel-unknown-linux-musl]
linker = "mipsel-openwrt-linux-musl-gcc"
```
