### ISSUE TITLE
Why does a call that fails due to inssuficient fuel not consume _any_ fuel?

### ISSUE THREAD

**Issue by wucke13** [paritytech/wasmi#698]

**Comment by Robbepop** [comment]
Hi @wucke13 it seems I need plenty more information about the problem that you are describing.
Generally a call should consume fuel and if given to little fuel it should additionally bail out with an `OutOfFuel` trap.
Before consuming fuel per basic block (a sequence of connected instructions) it is checked that the caller has given enough fuel and only execute those instructions in the basic block if enough fuel was given. If not enough fuel was given no instruction is executed and also no fuel is consumed.

**Comment by Robbepop** [comment]
For future questions about `wasmi` I'd recommend posting in the `wasmi`'s discussion: https://github.com/paritytech/wasmi/discussions

**Comment by wucke13** [comment]
So, if a wasm function does not contain branches, the hole thing becomes a single block? I was confused how you cloud know a priori that the fuel will not be sufficient, but I think I get it now.

**Comment by Robbepop** [comment]
> So, if a wasm function does not contain branches, the hole thing becomes a single block? I was confused how you cloud know a priori that the fuel will not be sufficient, but I think I get it now.

Yeah that is kinda right. The function translation process tries to group instructions together as good as it can and charges in bulk for all instructions in that group at once. This is done as optimization since otherwise the overhead for fuel metering would be significant.
Some of the instructions from the `bulk-memory` and `reference-types` Wasm proposals do not have a known cost at translation time and thus require fuel metering during execution time. However, for those instructions it is totally fine to incur overhead at runtime since they are quite massive.
