### ISSUE TITLE
Implement the Wasm `module-linking` proposal

### ISSUE THREAD

**Issue by clearloop** [paritytech/wasmi#742]
It has already been a part of wasm (component but not core) [spec][0] tests, however WASMI [has not supported it yet][1] while both wasmer and wasmtime support it

wondering if this has a priority, or ur welcome others' PRs

[0]: https://github.com/WebAssembly/testsuite/blob/main/linking.wast
[1]: https://github.com/paritytech/wasmi/blob/master/crates/wasmi/src/module/parser.rs#L282

**Comment by Robbepop** [comment]
Do you have a use case for the Wasm `component-model` for `wasmi`?

So far nobody has requested this feature. My employer (Parity Technologies) is not in need of this so it is rather low priority although we still want to implement all of the stabilized Wasm proposals in `wasmi` eventually to stay complete and up to date.

Another reason why I have not yet thought about implementing the Wasm `module-linking` is that I thought it was superseeded by Wasm `component-model` and wanted to wait for dust to settle and things to stabilize.

**Comment by clearloop** [comment]
> Do you have a use case for the Wasm module-linking for wasmi?

exactly, for example pallet contract, we can separate the dlmalloc-rs and ink logic to shared libraries to trim the size of contracts

**Comment by Robbepop** [comment]
I spoke with the rest of the smart contracts team at Parity and we came to the conclusion that indeed this Wasm proposal might be useful to us as well for delegate calling libraries.

That said the priority of implementing the Wasm `module-linking` proposal is still not high for us. Reasons are that there are more pressing things to be done, especially with the upcoming `wasmi` audit in August, the register-machine engine implementation and the planned lazy compilation strategy to significantly improve execution and startup times.

However, with the conclusion that this feature indeed is useful we might consider implementing it with medium-priority (instead of low-priority) even though it is unstable and so far we refrained from implementing unstable Wasm proposals at all.

What the @gear-tech team could do until then is as follows:

1. Fork `wasmi` and implement Wasm `module-linking` there with the chance of upstreaming it into mainline `wasmi`.
1. Try to find a work around that does not utilize Wasm `module-linking` proposal by providing tooling support (Due to missing knowledge about the big picture of the Wasm `module-linking` proposal I am uncertain if this is feasible.)
1. Wait for me (or another `wasmi` contributor) to do the job. 🙃

**Comment by jakehemmerle** [comment]
We're using Substrate at Entropy but had to rule out `wasmi` for our off-chain application environment because it's missing support for the components model (WIT stuff). We're using `wasmtime` currently, but would strongly consider `wasmi`, especially since it's audited.

Also, yes, [module linking proposal has been superseded by the component model proposal](https://github.com/WebAssembly/module-linking/#module-linking-proposal-for-webassembly), and that would be the proper implementation.

**Comment by Robbepop** [comment]
> We're using Substrate at Entropy but had to rule out `wasmi` for our off-chain application environment because it's missing support for the components model (WIT stuff). We're using `wasmtime` currently, but would strongly consider `wasmi`, especially since it's audited.
> 
> Also, yes, [module linking proposal has been superseded by the component model proposal](https://github.com/WebAssembly/module-linking/#module-linking-proposal-for-webassembly), and that would be the proper implementation.

If you are primarily missing "WIT stuff" I would like to copy'n'paste this link for you again since it might be of interest to you until `wasmi` properly implements the Wasm `module-linking` proposal: https://github.com/paritytech/wasmi/discussions/703

**Comment by Robbepop** [comment]
I just renamed this to be about adding Wasm `component-model` support since `module-linking` has been superseeded by it.

**Comment by Robbepop** [comment]
Closed in favor of https://github.com/paritytech/wasmi/issues/897 since Wasm `module-linking` got deprecated and was superseeded by the newer Wasm `component-model` proposal.
