### ISSUE TITLE
`ResumableInvocation` doesn't implement `Sync`

### ISSUE THREAD

**Issue by tomaka** [paritytech/wasmi#869]
I have the impression that all types of `wasmi` implement `Send` and `Sync`.
One notable exception is `ResumableInvocation`, that doesn't implement `Sync`.

In smoldot, I have to go through some hoops in order to bypass this problem, but maybe it's just an oversight?

**Comment by Robbepop** [comment]
I just checked it.
The `ResumableInvocation` is not `Sync` because its inner `Stack` field is not `Sync` which isn't `Sync` because `CallStack` is not `Sync` which is not `Sync` because `CallFrame` is not `Sync` due to holding raw pointers to stuff in the `Engine`. However, since `ResumableInvocation` is owning an `Engine` handle I think it should be safe to assume that it is `Sync`, right?

**Comment by tomaka** [comment]
Well, I don't know the internals of wasmi.

`Sync` simply means that the same `&ResumableInvocation` can be accessed from multiple different threads at the same time.
To me the question isn't really whether `ResumableInvocation` should be `Sync`, but at which level in the stack of types the `Sync` implementation is missing.

The reason why raw pointers in Rust don't automatically implement `Send` and `Sync` is because the language designers want library unsafe code users to the fact that they should be aware of `Send` and `Sync`. Raw pointers themselves are completely `Send` and `Sync`.

**Comment by Robbepop** [comment]
> `Sync` simply means that the same `&ResumableInvocation` can be accessed from multiple different threads at the same time.

That should be totally fine, especially since you cannot even do much with a mere `&` reference.
