### ISSUE TITLE
Example showing shared linear memory use

### ISSUE THREAD

**Issue by autodidaddict** [paritytech/wasmi#95]
Can you show an example of having the host read/write data to a linear memory that was imported by the wasm module and not contained within? 

As an example, [this demo here](https://www.hellorust.com/demos/import-memory/index.html) shows how this string round-trip through linear memory is done when the host is JavaScript. I would love to be able to do the same thing with Rust as my host and am looking for an example of how to accomplish this in `wasmi` but I'm not finding a clear direction in the docs.

**Comment by pepyakin** [comment]
Unfortunately, I can't provide an example that focused on precisely this.

You can take a look on [this test](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L399).

The basic idea is similar to the JS example. Just [return a memory instance](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L438) when the [module imports it](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L474), still retaining a reference to it.

**Comment by autodidaddict** [comment]
Okay I'll take a look at those tests and see if I can duplicate the sample. I didn't know that `resolve_memory` was a thing, so this definitely gets me closer. Thanks!

**Comment by autodidaddict** [comment]
What I am struggling with is the demo I linked to shows using a pointer directly as a parameter in the function and doesn't seem to be using the linear memory directly ... like there's some macro magic at play that I can't see.

**Comment by pepyakin** [comment]
No, you right : ) There is no magic because there is no usage of linear memory in the example (because of this I warned you that I can't provide a good example). 

I think then better to start with [`TestHost` example](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L32). It [has a reference](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L33) to a `MemoryInstance`. Test host uses the `MemoryInstance` to implement functions [`inc_mem`](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L99-L109) and [`get_mem`](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L112-L120) in it's `Externals` implementation.

But, unlike the previous example, `TestHost` [doesn't export](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L198-L200) a memory instance. To actually make it export a memory instance, we can simply use the construction like in the [previous example](https://github.com/paritytech/wasmi/blob/f305b3cd1f0c5b035e6f7034e632d22637b768f9/src/tests/host.rs#L437-L443)

**Comment by autodidaddict** [comment]
Whenever I create a Rust lib and put wasm_import_memory at the top, the resulting wasm produced by the compiler still appears to export memory... I don't see a 
```
(import "env" "memory" (memory (;0;) 17))
```
line like the demos show from the link above.

**Comment by pepyakin** [comment]
Ah, yeah. Try to add `#![wasm_import_memory]` attribute to the `lib.rs` of your project.

**Comment by autodidaddict** [comment]
I also can't get it to compile without putting `#![feature(custom_attribute)]` at the top, and none of the samples of this attribute seem to do that.

**Comment by andrewdavidmackenzie** [comment]
I was struggling to find good examples of doing this also....so empathise!

It's not using an imported linear memory (it's using one created internally, that you specify on getting Module, and then get via export) but this repo of mine trying to figure out the same thing maybe useful to you:

https://github.com/andrewdavidmackenzie/wasmi-string

For my project I don't want to pass/get Strings, but a more complex signature & return, so I advanced that a bit (using serde to serialize/deserialize - which suits my project) and pass anything that can be expressed in Serde to/from a function in the wasm module): 

https://github.com/andrewdavidmackenzie/wasm_explore
